### ISSUE TITLE
ZLayer.make fails with covariant type constructors on Scala 3

### ISSUE THREAD

**Issue by evis** [zio/zio#10179]
## Problem

On Scala 3, when services are parameterized by a covariant type constructor (`C[+A]`), `ZLayer.make` fails to assemble multiple dependencies because the requirements collapse from `C[A1] & C[A2]` into a single `C[A1 & A2]`. The same code compiles on Scala 2.13.

This aligns with Scala 3 intersection simplification rules (C covariant ⇒ `C[A] & C[B] ~> C[A & B]`), but it makes the common pattern "inject two clients of the same covariant family" non-workable with `ZLayer.make`.

## Minimal reproduction

```scala
// variance.sc
import zio._

trait A1
trait A2
trait GrpcClient[+A]

class RequiresTwoClients(a1Client: GrpcClient[A1], a2Client: GrpcClient[A2])

def a1: GrpcClient[A1] = new GrpcClient[A1] {}
def a2: GrpcClient[A2] = new GrpcClient[A2] {}

ZLayer.make[RequiresTwoClients](
  ZLayer.succeed(a1),
  ZLayer.succeed(a2),
  ZLayer.derive[RequiresTwoClients]
)
```

### Commands

**Scala 2.13 — OK**
```bash
scala-cli variance.sc --dependency dev.zio::zio:2.1.21 --scala 2.13.16
```

**Scala 3 — Fails**
```bash
scala-cli variance.sc --dependency dev.zio::zio:2.1.21 --scala 3.7.2
```

## Actual behavior (Scala 3)

Compilation error (shortened):

```
──── ZLAYER ERROR ────────────────────────────────────────────────────
Please provide a layer for the following type:

  1. GrpcClient[A1 & A2]
```

So the requirement `GrpcClient[A1] & GrpcClient[A2]` is simplified to `GrpcClient[A1 & A2]`, which we didn't (and can't reasonably) provide.

## Expected behavior

`ZLayer.make` should be able to assemble two distinct services `GrpcClient[A1]` and `GrpcClient[A2]` into the target `RequiresTwoClients` even when `GrpcClient` is covariant, just like it does on Scala 2.13.

## Notes

- The same code works if `GrpcClient` is invariant (`trait GrpcClient[A]`)
- The problem appears in `ZLayer.make` itself on Scala 3 due to intersection type simplification (the issue persists even when replacing `ZLayer.derive` with `ZLayer.fromFunction`)

## Question

Is there a way for `ZLayer.make` to preserve distinct requirements of the same covariant constructor instead of collapsing them?

## Environment

- ZIO version: 2.1.21
- Scala version: 3.7.2 (works on 2.13.16)
