### ISSUE TITLE
ZIO 2.0.0-RC3 compilation issue - withFilter is not a member of zio.ZIO[...] (tuple success type)

### ISSUE THREAD

**Issue by pjfanning** [zio/zio#6468]
https://github.com/pjfanning/zio-metrics-micrometer/blob/zio2/src/test/scala/com/github/pjfanning/zio/micrometer/unsafe/MicrometerUnsafeTest.scala#L70

(note that this is zio2 branch as opposed to main branch)

This compiles ok with ZIO 1 and ZIO 2.0.0-RC2 but fails with this in ZIO 2.0.0-RC3

```
[info] compiling 2 Scala sources to /Users/pj.fanning/code/zio-metrics-micrometer/target/scala-2.13/test-classes ...
[error] /Users/pj.fanning/code/zio-metrics-micrometer/src/test/scala/com/github/pjfanning/zio/micrometer/unsafe/MicrometerUnsafeTest.scala:70:27: value withFilter is not a member of zio.ZIO[com.github.pjfanning.zio.micrometer.unsafe.Registry,Throwable,(io.micrometer.core.instrument.Meter.Id, io.micrometer.core.instrument.Meter.Id)]
[error]             (id1, id2) <- counterZipTestZIO
```

Would someone be able to have a look? The other ZIO tasks are ok, just this one that has a tuple as the success type seems an issue.

**Comment by adamgfraser** [comment]
This is intended behavior. Unfortunately due to a quirk in the Scala compiler destructuring like this within a for comprehension is translated into `withFilter` calls which require us to handle the possibility that the filter function could fail even though in cases like this we know at the type level that the restructuring will always succeed.

There is no way to represent this error possibility in polymorphic code and this issue needs to be addressed at the Scala compiler level. See #6328 for further discussion.

**Comment by pjfanning** [comment]
thanks @adamgfraser - now that I understand the issue I can workaround this with

```
          for {
            tuple <- counterZipTestZIO
            (id1, id2) = tuple
          } yield assert(id1)(equalTo(id2))
```

**Comment by adamgfraser** [comment]
@pjfanning Exactly!
