### ISSUE TITLE
[ZIO 2.0.14] [Scala 3.3] ZLayer.makeSome regression

### ISSUE THREAD

**Issue by alphaho** [zio/zio#8168]
Hi,

I've found a regression in `ZLayer.makeSome` after upgrading to ZIO 2.0.14 when I use Scala 3.3.

Below snippet compiles with ZIO 2.0.13 but fails with 2.0.14:

```scala
import zio._

object LayerMacroRegression extends ZIOAppDefault {
  val intLayer: ZLayer[Char, Nothing, Int] = ZLayer {
    ZIO.serviceWith[Char](_.toInt)
  }

  val stringLayer: ZLayer[Boolean, Nothing, String] = ZLayer {
    ZIO.serviceWith[Boolean](_.toString)
  }

  val layer: ZLayer[Char with Boolean, Nothing, Int with String] = ZLayer.makeSome[Char with Boolean, Int with String](
    intLayer,
    stringLayer
  )
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = (for {
    serviceInt    <- ZIO.service[Int]
    serviceString <- ZIO.service[String]
    _             <- ZIO.logInfo(s"serviceInt: $serviceInt, serviceString: $serviceString")
  } yield ())
    .provide(
      layer,
      ZLayer.succeed('5'),
      ZLayer.succeed(true)
    )
}
```

It fails with the below compilation error:

```
[error] 14 |  val layer: ZLayer[Char with Boolean, Nothing, Int with String] = ZLayer.makeSome[Char with Boolean, Int with String](
[error]    |                                                                   ^
[error]    |
[error]    |
[error]    |  ──── ZLAYER ERROR ────────────────────────────────────────────────────
[error]    |
[error]    |   Please provide a layer for the following type:
[error]    |
[error]    |     Required by intLayer
[error]    |     1. scala.Char & scala.Boolean
[error]    |
[error]    |     Required by stringLayer
[error]    |     1. scala.Char & scala.Boolean
[error]    |
[error]    |  ──────────────────────────────────────────────────────────────────────
[error]    |
[error] 15 |    intLayer,
[error] 16 |    stringLayer
[error] 17 |  )
```

**Comment by guizmaii** [comment]
Thanks for your report @alphaho :)

Your issue might already have been reported and fixed. See https://github.com/zio/zio/issues/8164

Can you try with the latest snapshot to see if it fixes your issue?
Here's how to use it. In your `build.sbt`, add:

```scala
resolvers ++= Resolver.sonatypeOssRepos("snapshots")
```

And update the ZIO version to: `2.0.14+1-a6ce7326-SNAPSHOT` (comes from here: https://github.com/zio/zio/actions/runs/5146655237/jobs/9266788269)

**Comment by alphaho** [comment]
Thanks @guizmaii ! 
I should have checked the closed issue as well after I checked the opened ones.
I tried the snapshot version and confirmed it works. I'm closing this issue now.
