### ISSUE TITLE
After bump to 1.0.0-RC11-1 missing class `TaskR` in the cats intro

### ISSUE THREAD

**Issue by LukaszByczynski** [zio/zio#1357]
Hi,

After bump to the latest version (1.0.0-RC11-1) I have found an issue with `zio-interop-cats`.

```
java.lang.ClassNotFoundException: zio.TaskR$
```

Probably, the simple fix will be to upgarde interop-cats project to the same version of the ZIO, and remove usage TaskR from the code. 

I can push a fix for that, but I would like to ensure..

**Comment by ghostdogpr** [comment]
I released `cats-interop` yesterday as well: https://github.com/zio/interop-cats/releases/tag/v2.0.0.0-RC2

If you use that version, the error will disappear.

**Comment by ghostdogpr** [comment]
Closing, let me know if you still have issues with the version I mentioned.

**Comment by LukaszByczynski** [comment]
Unfortunatelly I'm FS2 uses version 1.3.0. Can you push updated interop either for cats 1.3.1 ?

**Comment by ghostdogpr** [comment]
Cats and cats effect 2.0 maintain binary compatibility with 1.x so it should be ok for you to use it with FS2. You can see cats 2.0-RC1 release notes for details.

**Comment by LukaszByczynski** [comment]
After bump I still have problems:

```java.lang.NoClassDefFoundError: cats/effect/ContextShift$class
[error] 	at zio.interop.CatsInstances$$anon$7.<init>(catsjvm.scala:54)
[error] 	at zio.interop.CatsInstances.zioContextShift(catsjvm.scala:54)```

From my perspective, I would like to avoid mixing RC versions of ZIO with Cats 2.x RC

**Comment by ghostdogpr** [comment]
cats-interop 2.0.0.0-RC2 is built with ZIO 1.0.0-RC11-1 and cats-effect 2.0.0-M5. I personally had that combination working well at work and upgraded to cats-effect 2.0.0-RC1 today without issue. Do you have the same ones?

AFAIK, there is no branch of cats-interop based on cats 1.x. I think a final version of cats-effect 2.0 is imminent.
