### ISSUE TITLE
toLayer not found on parameterless case class

### ISSUE THREAD

**Issue by nickelsen** [zio/zio#5170]
Code from the [micro-site on module pattern 2.0](https://zio.dev/docs/datatypes/contextual/#module-pattern-20):

```
import zio._

trait Logging {
  def log(line: String): UIO[Unit]
}

case class LoggingLive() extends Logging {
  override def log(line: String): UIO[Unit] =
    ZIO.effectTotal(print(line))
}

object LoggingLive {
  val layer: ULayer[Has[Logging]] = LoggingLive().toLayer
}
```

When compiling the above code on ZIO 1.0.9, the compiler says that:
```
value toLayer is not a member of LoggingLive
```

It compiles if the layer is defined as follows:
```
val layer: ULayer[Has[Logging]] = (LoggingLive.apply _).toLayer
```

**Comment by ajrnz** [comment]
I came across the same problem but would add that it works on scala 2.13 but fails on scala 3. The above fix works though.

**Comment by adamgfraser** [comment]
We deleted this operator.
