### ISSUE TITLE
Infinite loop when exception is thrown during execution of `ZIO.failCause`

### ISSUE THREAD

**Issue by yoohaemin** [zio/zio#10208]
Hi all, I've got a problem I'd like to discuss.

It's a little difficult to figure out how the JVM ended up in this state (related to Mill's classloader manipulation while running tests), but we're having an infinite loop inside `FiberRuntime`.

### Mechanism of failure

It goes on like this:

- Something fails when evaluating `runLoop` and throws
- It is caught here wrapped in `ZIO.failCause`

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/FiberRuntime.scala#L466-L473

- `failCause` calls `generateStackTrace()`

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/ZIO.scala#L3254-L3261

- Then it tries to create stack traces:

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/FiberRuntime.scala#L535-L536

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/FiberRuntime.scala#L1700-L1702

- In some of the threads it's not initialized, so `initialValue` is called, constructing `StackTraceBuilder`. Then `ClassTag$.MODULE$` is accessed

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/StackTraceBuilder.scala#L24-L25

- NoClassDefFoundError on `ClassTag$.MODULE$` (Due to something unrelated changing the classloader's state)
- `FiberRuntime.evaluateEffect` catches it: `catch { case throwable => /* if not fatal */ effect = ZIO.failCause(...) }`
- Wrapping in `failCause` calls `generateStackTrace()` again
- Cycles back to ThreadLocal → same error → infinite loop

### Suggestion

`LinkageError` can happen inside ZIO internals like `VirtualMachineError` due to classloader issues, and once it happens it causes an infinite loop. I suggest we make it fatal as well.

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/IsFatal.scala#L24-L31

### Questions

`git bisect` points me to this PR that starts triggering the infinite loop. https://github.com/zio/zio/pull/9899

But I'm still having a hard time understanding how this change is causing it; `NoClassDefFoundError` was not fatal before and after this commit. But I've reproduced many times enough that I'm absolutely certain this commit is the cause of the error. Specifically this change:

https://github.com/zio/zio/pull/9899/files#diff-cf744392bf20a036955585beaf7ff962f0dafe9efd73cac82e6ecb440bde2243

(changing `==` to `eq` seems to be benign in my case)

My hunch is that this commit didn't "cause" the issue but merely unearthed it, related to this specific race condition inside mill test runner.

It seems I'm not the only person hitting this problem: https://discord.com/channels/629491597070827530/630498701860929559/1431993477025108082

I don't have a reproducer handy right now, it seems to happen in big mill builds and I didn't have time to prepare one. But I hope the mechanism I explained is clear.

**Comment by kyri-petrou** [comment]
I think the issue here goes a bit deeper, and considering `LinkageError` as fatal might be patch to the issue until we end up with another kind of error that could be thrown during error handling that we're not considering fatal.

I wonder if a potentially simpler solution would be to do something like this:

```scala
  def failCause[E](cause: => Cause[E])(implicit trace0: Trace): IO[E, Nothing] =
    ZIO.withFiberRuntime[Any, E, Nothing] { (state, _) =>
      try {
        val trace = state.generateStackTrace()
        val refs  = state.getFiberRefs(false)
        val spans = refs.getOrDefault(FiberRef.currentLogSpan)
        val anns  = refs.getOrDefault(FiberRef.currentLogAnnotations)
        Exit.failCause(cause.applyAll(trace, spans, anns))
      } catch {
        case t: Throwable => Exit.die(t) // or throw a custom Exception that we consider Fatal
      }
    }
```

It's a bit hard to guarantee that this works without a reproducer, but I think it would work without having to alter the behaviour of `IsFatal`.

**Comment by kyri-petrou** [comment]
One thing I should also point out is that `NoSuchMethodError` is a subclass of `LinkageError`, so if we were to consider `LinkageError` as fatal then we'd potentially be breaking code that relies on reflection, e.g.,:

```scala
ZIO.attempt(someObj.getClass.getMethod("someMethod"))
```

**Comment by yoohaemin** [comment]
Excellent points. A custom exception that holds both `t` and `cause: Cause[E]` and considered internally as fatal should work. Let me try it locally today to verify it fixes the problem and come up with a second PR.

**Comment by hearnadam** [comment]
@yoohaemin are you still interested in working on this?

**Comment by yoohaemin** [comment]
Got a but distracted with other things. I already have a branch, will open a PR soon! Sorry for the delay 🙏

**Comment by hearnadam** [comment]
@yoohaemin can you reproduce after the semi-recent changes to IsFatal?

**Comment by yoohaemin** [comment]
We finally got to update the versions. It's good now! Thank you very much 🙏
