### ISSUE TITLE
Binary incompatibility of zio-streams:2.1.7 with zio:2.1.9

### ISSUE THREAD

**Issue by geny200** [zio/zio#9208]
Hello, we discovered a problem after updating zio to 2.1.9. At runtime we started to catch NoSuchMethodError from zio. After investigation we wrote a minimal example with bug reproduction (to run, use scala-cli):
```scala
//> using scala 2.13.14
//> using dep dev.zio::zio:2.1.9
//> using dep dev.zio::zio-streams:2.1.7

// to fix the problem, upgrade zio-streams version to 2.1.9. Or change scala version to 3.5.0

import zio.stream.ZStream
import zio.{Chunk, Scope, ZIO, ZIOAppArgs, ZIOAppDefault}

object Main extends ZIOAppDefault {

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] =
    // minimal example is `ZStream.repeatZIOChunkOption(ZIO.succeed(Chunk(10))).runDrain`
    ZStream
      .repeatZIOChunkOption(ZIO.succeed(Chunk(10)))
      .find(_ > 5)
      .runForeach(i => ZIO.consoleWith(_.printLine(i)))

}
```
error:
```bash
level=ERROR thread=#zio-fiber-2091259331 message="" cause="Exception in thread "zio-fiber-" java.lang.NoSuchMethodError: 'zio.ZIO zio.ZIO.$anonfun$foldZIO$1(scala.Function1, java.lang.Object, zio.Cause)'
        at zio.stream.ZStream$.$anonfun$repeatZIOChunkOption$1(ZStream.scala:4951)
        at zio.stream.ZStream$.$anonfun$unfoldChunkZIO$1(ZStream.scala:5092)
        at zio.stream.internal.ChannelExecutor.run(ChannelExecutor.scala:152)
        at zio.stream.internal.ChannelExecutor$.read$1(ChannelExecutor.scala:730)
        at zio.stream.internal.ChannelExecutor$.$anonfun$readUpstream$10(ChannelExecutor.scala:771)
        at zio.ZIO.$anonfun$$times$greater$1(ZIO.scala:89)"
```

**Comment by geny200** [comment]
Initially we got the problem when executing HTTP requests. Here is an example:
```scala
//> using scala 2.13.14
//> using dep com.softwaremill.sttp.client4::core:4.0.0-M17
//> using dep com.softwaremill.sttp.client4::zio:4.0.0-M17
//> using dep dev.zio::zio:2.1.9

// to fix the problem, uncomment the following line. Or change scala version to 3.5.0
////> using dep dev.zio::zio-streams:2.1.9

import sttp.client4.UriContext
import sttp.client4.httpclient.zio.HttpClientZioBackend
import sttp.client4.quick.quickRequest
import zio.{Scope, ZIO, ZIOAppArgs, ZIOAppDefault}

object Main extends ZIOAppDefault {

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] =
    HttpClientZioBackend().flatMap { backend =>
      for {
        response <- quickRequest.get(uri"http://httpbin.org/ip").send(backend).map(_.body)
        _ <- ZIO.consoleWith(_.printLine(response))
      } yield ()
    }

}
```
error:
```bash
level=ERROR thread=#zio-fiber-1798237993 message="" cause="Exception in thread "zio-fiber-" java.lang.NoSuchMethodError: 'zio.ZIO zio.ZIO$.$anonfun$uninterruptible$1(scala.Function0, java.lang.Object)'
        at zio.stream.internal.ChannelExecutor.runBracketOut(ChannelExecutor.scala:438)
        at zio.stream.internal.ChannelExecutor.run(ChannelExecutor.scala:234)
        at zio.stream.internal.ChannelExecutor$.read$1(ChannelExecutor.scala:730)
        at zio.stream.internal.ChannelExecutor$.$anonfun$readUpstream$10(ChannelExecutor.scala:771)
        at zio.ZIO.$anonfun$$times$greater$1(ZIO.scala:89)"
```

**Comment by Ragge-dev** [comment]
Thanks a lot for creating this issue with the examples @geny200, it saved me a lot of work!

**Comment by kyri-petrou** [comment]
Closing as this was fixed in #9223
