### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: zio/internal/macros from 2.0.2 -> 2.0.3: 

### ISSUE THREAD

**Issue by jasiskis** [zio/zio#7511]
Hi, 

I  have a Flink application built with scala 3.2.0 and ZIO. I'm using ZIO mainly on the edges and inside one Flink AsyncOperator. This AsyncOperator has to serialize the code to distribute to task managers.

Everything was working fine up until ZIO 2.0.2, when I bumped to 2.0.3 I started getting errors like the below:

```
2022-11-08 15:34:18,472 ERROR org.apache.flink.client.cli.CliFrontend                      [] - Fatal error while running command line interface.
java.lang.NoClassDefFoundError: zio/internal/macros
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
java.lang.NoClassDefFoundError: zio/internal/macros
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)	at java.lang.Class.getDeclaredMethod(Class.java:2473) ~[?:?]

	at java.io.ObjectStreamClass.getInheritableMethod(ObjectStreamClass.java:1548) ~[?:?]
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:521) ~[?:?]
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:484) ~[?:?]
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:381) ~[?:?]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1135) ~[?:?]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[?:?]
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:632) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:143) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:132) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:69) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:2194) ~[flink-	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.datastream.AsyncDataStream.addOperator(AsyncDataStream.java:84) ~[flink-dist-1.15.2.jar:1.15.2]

	at org.apache.flink.streaming.api.datastream.AsyncDataStream.orderedWait(AsyncDataStream.java:146) ~[flink-dist-1.15.2.jar:1.15.2]
	at core.api.datastream.wrappers.DataStream.orderedAsync(DataStream.scala:73) ~[?:?]
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)	at magneton.workflows.external2internal.FromTransferPixToCustomerEdgePipeline.pipeline(FromTransferPixToCustomerEdgePipeline.scala:84) ~[?:?]

	at magneton.workflows.ExternalToInternalPixWorkflow.defineWorkflow(ExternalToInternalPixWorkflow.scala:41) ~[?:?]
	at com.nu.magneton.Main$package$.$anonfun$2$$anonfun$1(Main.scala:51) ~[?:?]
	at java.base/java.io.ObjectStreamClass.getInheritableMethod(ObjectStreamClass.java:1548)
	at zio.ZIO$ServiceWithPartiallyApplied$.apply$extension$$anonfun$12(ZIO.scala:5063) ~[?:?]
	at java.base/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:521)
	at zio.ZIO$ServiceWithZIOPartiallyApplied$.apply$extension$$anonfun$13$$anonfun$1(ZIO.scala:5075) ~[?:?]
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:918) ~[?:?]
	at java.base/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:918) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(Native Method)	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:918) ~[?:?]

	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:384) ~[?:?]
	at java.base/java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:484)	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:496) ~[?:?]

	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:224) ~[?:?]
	at java.base/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:381)	at zio.internal.FiberRuntime.run(FiberRuntime.scala:137) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1135)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)	at java.lang.Thread.run(Thread.java:829) ~[?:?]

	Suppressed: zio.Cause$FiberTrace: Exception in thread "zio-fiber-1" java.lang.NoClassDefFoundError: zio/internal/macros
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:632)	at com.nu.magneton.Main$package.main.program(Main.scala:52)

	at com.nu.magneton.Main$package.main.program(Main.scala:54)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:143)	at com.nu.magneton.Main$package.main.program(Main.scala:56)

	at com.nu.magneton.Main$package.main(Main.scala:97)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:132)	at com.nu.magneton.Main$package.main(Main.scala:116)

	Suppressed: java.lang.ClassNotFoundException: zio.internal.macros
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:69)

Caused by: java.lang.ClassNotFoundException: zio.internal.macros
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:2194)	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]

	at org.apache.flink.streaming.api.datastream.AsyncDataStream.addOperator(AsyncDataStream.java:84)	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:68) ~[flink-dist-1.15.2.jar:1.15.2]

	at org.apache.flink.streaming.api.datastream.AsyncDataStream.orderedWait(AsyncDataStream.java:146)	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74) ~[flink-dist-1.15.2.jar:1.15.2]

	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:52) ~[flink-dist-1.15.2.jar:1.15.2]
	at core.api.datastream.wrappers.DataStream.orderedAsync(DataStream.scala:73)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 34 
```

I tried spotting what could have changed from 2.0.2 -> 2.0.3 that could cause such an error but couldn't figure it out.

Help would be appreciated.

**Comment by guizmaii** [comment]
@jasiskis Is it still a problem with more recent versions of ZIO?

**Comment by hearnadam** [comment]
This is likely caused by mismatched ZIO versions. Can you make sure you're on the same version throughout and try again? Reopen if you still face this issue.
