### PR TITLE
Make LinkageError fatal

### LINKED ISSUE #10208: Infinite loop when exception is thrown during execution of `ZIO.failCause`
Hi all, I've got a problem I'd like to discuss.

It's a little difficult to figure out how the JVM ended up in this state (related to Mill's classloader manipulation while running tests), but we're having an infinite loop inside `FiberRuntime`.

### Mechanism of failure

It goes on like this:

- Something fails when evaluating `runLoop` and throws
- It is caught here wrapped in `ZIO.failCause`

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/FiberRuntime.scala#L466-L473

- `failCause` calls `generateStackTrace()`

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/ZIO.scala#L3254-L3261

- Then it tries to create stack traces:

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/FiberRuntime.scala#L535-L536

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/FiberRuntime.scala#L1700-L1702

- In some of the threads it's not initialized, so `initialValue` is called, constructing `StackTraceBuilder`. Then `ClassTag$.MODULE$` is accessed

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/StackTraceBuilder.scala#L24-L25

- NoClassDefFoundError on `ClassTag$.MODULE$` (Due to something unrelated changing the classloader's state)
- `FiberRuntime.evaluateEffect` catches it: `catch { case throwable => /* if not fatal */ effect = ZIO.failCause(...) }`
- Wrapping in `failCause` calls `generateStackTrace()` again
- Cycles back to ThreadLocal → same error → infinite loop

### Suggestion

`LinkageError` can happen inside ZIO internals like `VirtualMachineError` due to classloader issues, and once it happens it causes an infinite loop. I suggest we make it fatal as well.

https://github.com/zio/zio/blob/26539d860a7d831bdb406ce52c305973a69f39f8/core/shared/src/main/scala/zio/internal/IsFatal.scala#L24-L31

### Questions

`git bisect` points me to this PR that starts triggering the infinite loop. https://github.com/zio/zio/pull/9899

But I'm still having a hard time understanding how this change is causing it; `NoClassDefFoundError` was not fatal before and after this commit. But I've reproduced many times enough that I'm absolutely certain this commit is the cause of the error. Specifically this change:

https://github.com/zio/zio/pull/9899/files#diff-cf744392bf20a036955585beaf7ff962f0dafe9efd73cac82e6ecb440bde2243

(changing `==` to `eq` seems to be benign in my case)

My hunch is that this commit didn't "cause" the issue but merely unearthed it, related to this specific race condition inside mill test runner.

It seems I'm not the only person hitting this problem: https://discord.com/channels/629491597070827530/630498701860929559/1431993477025108082

I don't have a reproducer handy right now, it seems to happen in big mill builds and I didn't have time to prepare one. But I hope the mechanism I explained is clear.

### PR DESCRIPTION
**Pull request by yoohaemin**
close #10208

### CODE REVIEW

File: core/shared/src/main/scala/zio/internal/IsFatal.scala [hunk 1]
```diff
@@ -23,6 +23,7 @@ private[zio] sealed trait IsFatal extends (Throwable => Boolean) { self =>
   @deprecated("IsFatal is deprecated, kept only for binary compatability.", "2.1.21")
   def apply(t: Throwable): Boolean =
     if (t.isInstanceOf[VirtualMachineError]) true
+    else if (t.isInstanceOf[LinkageError]) true
```
Comment (hearnadam) [inline core/shared/src/main/scala/zio/internal/IsFatal.scala:26]: Can you merge these branches? Or we can use a match.

**Comment by hearnadam** [comment]
Change seems fine to me, thanks for the detailed issue and the fix!

Do you think it's feasible to add a reproducing test?

**Comment by hearnadam** [comment]
Closing due to the issues brought up by Kyri https://github.com/zio/zio/issues/10208#issuecomment-3456960859
