### ISSUE TITLE
Binary incompatibility in 1.0.4: NoSuchMethodError currentTime

### ISSUE THREAD

**Issue by rtimush** [zio/zio#4581]
The following code fails with `java.lang.NoSuchMethodError: zio.clock.package$.$anonfun$currentTime$3(Lscala/Function0;Lzio/Has;)Lzio/ZIO;` with zio 1.0.4 and works with zio 1.0.3:

```scala
import zio._
import zio.clock._
import zio.interop.catz._
import java.util.concurrent._

Runtime.default.unsafeRunSync {
  cats.effect
    .Timer[ZIO[Clock, Any, *]]
    .clock
    .realTime(TimeUnit.MILLISECONDS)
}
```
Dependencies:
```
libraryDependencies ++= Seq(
  "org.typelevel" %% "cats-effect" % "2.3.1",
  "dev.zio" %% "zio" % "1.0.4",
  "dev.zio" %% "zio-interop-cats" % "2.2.0.1",
)
```
Scastie: https://scastie.scala-lang.org/FmuHgKbqSEaoGO96gkMBsA

It looks like a binary incompatibility.

**Comment by rtimush** [comment]
It seems that the root cause is in zio-cats-interop — it [allows inlining](https://github.com/zio/interop-cats/blob/master/project/BuildHelper.scala#L42) from `zio.*`

**Comment by rtimush** [comment]
Moved to https://github.com/zio/interop-cats/issues/282
