### ISSUE TITLE
Chunk.head throws NoSuchMethodException

### ISSUE THREAD

**Issue by domartynov** [zio/zio#4438]
```scala
Chunk.fromArray(Array(1,2,3)).head
```
throws:
```java
java.lang.NoSuchMethodError: scala.collection.IndexedSeqOps.head$(Lscala/collection/IndexedSeqOps;)Ljava/lang/Object;
  at zio.Chunk.head(Chunk.scala:40)
  ...
```

**Comment by atooni** [comment]
FYI: I have seen the same error when I was working on ZMX. It seems that with ZIO 1.0.1 it works, while the error is thrown after bumping the ZIO version to 1.0.3. Might help to narrow it down
